# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A function to calculate fibonacci numbers (implemented in C++)
#'
#' @param n The length of the sequence
#' @return A vector containing \code{n} fibonacci numbers
#' @examples
#' n <- 20;
#' gen_fib_cpp(n);
#' @export
gen_fib_cpp <- function(n) {
    .Call('spsintro_gen_fib_cpp', PACKAGE = 'spsintro', n)
}

#' Print C++ data type ranges to the R-console
#' @return No return values, simply printing to the R-console
#' @export
show_type_ranges <- function() {
    invisible(.Call('spsintro_show_type_ranges', PACKAGE = 'spsintro'))
}

#' Print C++ data type conversions
#' @return No return values, simply printing to the R-console
#' @export
type_conversions <- function() {
    invisible(.Call('spsintro_type_conversions', PACKAGE = 'spsintro'))
}

#' Show effect of mixing signed and unsigned types
#' @return No return values, simply printing to the R-console
#' @export
mix_signed_unsigned <- function() {
    invisible(.Call('spsintro_mix_signed_unsigned', PACKAGE = 'spsintro'))
}

#' Illustrate scoping rules
#' @return No return values, simply printing to the R-console
#' @export
illustrate_scope <- function() {
    invisible(.Call('spsintro_illustrate_scope', PACKAGE = 'spsintro'))
}

#' Function to illustrate references
#' @return No return values, simply printing to the R-console
#' @export
show_references <- function() {
    invisible(.Call('spsintro_show_references', PACKAGE = 'spsintro'))
}

#' Function to illustrate pointers
#' @return No return values, simply printing to the R-console
#' @export
show_pointers <- function() {
    invisible(.Call('spsintro_show_pointers', PACKAGE = 'spsintro'))
}

#' Illustrates definition and usage of a simple class with only data members
#' @param dbh The trees diameter at breast height (double)
#' @param height The trees height (double)
#' @param no_stems The number of stems the tree has (int)
#' @param spec_name The species of the tree (string)
#' @return No return values, simply printing to the R-console
#' @export
create_tree_struct <- function(dbh, height, no_stems, spec_name) {
    invisible(.Call('spsintro_create_tree_struct', PACKAGE = 'spsintro', dbh, height, no_stems, spec_name))
}

#' Convert all characters in a string to upper case
#' @param str A string
#' @return The same string as \code{str} but with upper case letters
#' @export
to_upper_range_for <- function(str) {
    .Call('spsintro_to_upper_range_for', PACKAGE = 'spsintro', str)
}

#' Convert all characters in a string to upper case
#' @param str A string
#' @return The same string as \code{str} but with upper case letters
#' @export
to_upper_subscript <- function(str) {
    .Call('spsintro_to_upper_subscript', PACKAGE = 'spsintro', str)
}

#' Add elements to a vector
#' @param n An integer giving the final size of the vector
#' @return A vector of size \code{n}
#' @export
add_elem <- function(n) {
    .Call('spsintro_add_elem', PACKAGE = 'spsintro', n)
}

#' Sums all elements in a vector
#' @param v A vector of doubles
#' @return A double containing the sum of all elements of \code{v}
#' @export
sum_elem <- function(v) {
    .Call('spsintro_sum_elem', PACKAGE = 'spsintro', v)
}

#' Square vector elements
#' @param v A vector of doubles
#' @return A double containing the sum of all elements of \code{v}
#' @export
squ_elem <- function(v) {
    .Call('spsintro_squ_elem', PACKAGE = 'spsintro', v)
}

#' Square vector elements
#' @param v A vector of doubles
#' @return A double containing the sum of all elements of \code{v}
#' @export
squ_elem_it <- function(v) {
    .Call('spsintro_squ_elem_it', PACKAGE = 'spsintro', v)
}

#' Array element access example
#' @return Nothing is returned, only printing to the console
#' @export
arr_access <- function() {
    invisible(.Call('spsintro_arr_access', PACKAGE = 'spsintro'))
}

#' Return remainder
#' @return The remainder of an integer division
#' @export
ret_rem <- function(a, b) {
    .Call('spsintro_ret_rem', PACKAGE = 'spsintro', a, b)
}

#' Conditional operator
#' @param x An int
#' @return Nothing to return, just printing to the console
#' @export
dem_cond <- function(x) {
    invisible(.Call('spsintro_dem_cond', PACKAGE = 'spsintro', x))
}

#' An if-else example
#' @param dbh Diameter at breast height in cm
#' @return A diameter class
#' @export
dem_if_else <- function(dbh) {
    .Call('spsintro_dem_if_else', PACKAGE = 'spsintro', dbh)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg <- function(x) {
    .Call('spsintro_find_first_neg', PACKAGE = 'spsintro', x)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg_for <- function(x) {
    .Call('spsintro_find_first_neg_for', PACKAGE = 'spsintro', x)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg_rf <- function(x) {
    .Call('spsintro_find_first_neg_rf', PACKAGE = 'spsintro', x)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg_dw <- function(x) {
    .Call('spsintro_find_first_neg_dw', PACKAGE = 'spsintro', x)
}

#' Demonstrate rounding in C++
#' R's built-in \code{round()} function shows a
#' different behaviour than the \code{round()} function of C++
#' @param x A double value to be rounded
#' @return The rounded integer represented as double
#' @export
round_cpp <- function(x) {
    .Call('spsintro_round_cpp', PACKAGE = 'spsintro', x)
}

#' Test Polygon classes
#' @return Return nothing
#' @export
test <- function() {
    invisible(.Call('spsintro_test', PACKAGE = 'spsintro'))
}

#' Return the area of an irregular polygon
#' @param x A vector of x-coordinates
#' @param y A vector of y-coordinates (positive \code{y}-vaues mean upwards)
#' @return The area of the polygon
#' @export
calc_poly_area <- function(x, y) {
    .Call('spsintro_calc_poly_area', PACKAGE = 'spsintro', x, y)
}

