# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A function to calculate fibonacci numbers (implemented in C++)
#'
#' @param n The length of the sequence
#' @return A vector containing \code{n} fibonacci numbers
#' @examples
#' n <- 20;
#' gen_fib_cpp(n);
#' @export
gen_fib_cpp <- function(n) {
    .Call('spsintro_gen_fib_cpp', PACKAGE = 'spsintro', n)
}

#' Find the maximum from a list of values
#'
#' @param x A vector holding a number of values
#' @return The largest number in \code{x}
#' @export
find_max <- function(x) {
    .Call('spsintro_find_max', PACKAGE = 'spsintro', x)
}

#' Calculate the distance between two observations based on a set of auxiliary
#' variables
#'
#' @param x_i Vector of auxiliary variables for observation \code{i}
#' @param x_j Vector of auxiliary variables for observation \code{j}
#' @param M A square matrix. When \code{M} is the identity matrix the
#' Euclidean distance results.
#' @export
calc_dist <- function(x_i, x_j, M) {
    .Call('spsintro_calc_dist', PACKAGE = 'spsintro', x_i, x_j, M)
}

#' Search nearest neighbours
#'
#' @param X Matrix with auxiliary variables of the reference set. Rows are the
#' single observations and variables are stored in columns.
#' @param M A square matrix defining the distance measure. When \code{M} is
#' the identity matrix, the Euclidean distance results.
#' @param k The number of neighbours
#' @export
find_knn <- function(Y, X, M, k) {
    .Call('spsintro_find_knn', PACKAGE = 'spsintro', Y, X, M, k)
}

#' Print C++ data type ranges to the R-console
#' @return No return values, simply printing to the R-console
#' @export
show_type_ranges <- function() {
    invisible(.Call('spsintro_show_type_ranges', PACKAGE = 'spsintro'))
}

#' Print C++ data type conversions
#' @return No return values, simply printing to the R-console
#' @export
type_conversions <- function() {
    invisible(.Call('spsintro_type_conversions', PACKAGE = 'spsintro'))
}

#' Show effect of mixing signed and unsigned types
#' @return No return values, simply printing to the R-console
#' @export
mix_signed_unsigned <- function() {
    invisible(.Call('spsintro_mix_signed_unsigned', PACKAGE = 'spsintro'))
}

#' Illustrate scoping rules
#' @return No return values, simply printing to the R-console
#' @export
illustrate_scope <- function() {
    invisible(.Call('spsintro_illustrate_scope', PACKAGE = 'spsintro'))
}

#' Function to illustrate references
#' @return No return values, simply printing to the R-console
#' @export
show_references <- function() {
    invisible(.Call('spsintro_show_references', PACKAGE = 'spsintro'))
}

#' Function to illustrate pointers
#' @return No return values, simply printing to the R-console
#' @export
show_pointers <- function() {
    invisible(.Call('spsintro_show_pointers', PACKAGE = 'spsintro'))
}

#' Illustrates definition and usage of a simple class with only data members
#' @param dbh The trees diameter at breast height (double)
#' @param height The trees height (double)
#' @param no_stems The number of stems the tree has (int)
#' @param spec_name The species of the tree (string)
#' @return No return values, simply printing to the R-console
#' @export
create_tree_struct <- function(dbh, height, no_stems, spec_name) {
    invisible(.Call('spsintro_create_tree_struct', PACKAGE = 'spsintro', dbh, height, no_stems, spec_name))
}

#' Convert all characters in a string to upper case
#' @param str A string
#' @return The same string as \code{str} but with upper case letters
#' @export
to_upper_range_for <- function(str) {
    .Call('spsintro_to_upper_range_for', PACKAGE = 'spsintro', str)
}

#' Convert all characters in a string to upper case
#' @param str A string
#' @return The same string as \code{str} but with upper case letters
#' @export
to_upper_subscript <- function(str) {
    .Call('spsintro_to_upper_subscript', PACKAGE = 'spsintro', str)
}

#' Add elements to a vector
#' @param n An integer giving the final size of the vector
#' @return A vector of size \code{n}
#' @export
add_elem <- function(n) {
    .Call('spsintro_add_elem', PACKAGE = 'spsintro', n)
}

#' Sums all elements in a vector
#' @param v A vector of doubles
#' @return A double containing the sum of all elements of \code{v}
#' @export
sum_elem <- function(v) {
    .Call('spsintro_sum_elem', PACKAGE = 'spsintro', v)
}

#' Square vector elements
#' @param v A vector of doubles
#' @return A double containing the sum of all elements of \code{v}
#' @export
squ_elem <- function(v) {
    .Call('spsintro_squ_elem', PACKAGE = 'spsintro', v)
}

#' Square vector elements
#' @param v A vector of doubles
#' @return A double containing the sum of all elements of \code{v}
#' @export
squ_elem_it <- function(v) {
    .Call('spsintro_squ_elem_it', PACKAGE = 'spsintro', v)
}

#' Array element access example
#' @return Nothing is returned, only printing to the console
#' @export
arr_access <- function() {
    invisible(.Call('spsintro_arr_access', PACKAGE = 'spsintro'))
}

#' Return remainder
#' @return The remainder of an integer division
#' @export
ret_rem <- function(a, b) {
    .Call('spsintro_ret_rem', PACKAGE = 'spsintro', a, b)
}

#' Conditional operator
#' @param x An int
#' @return Nothing to return, just printing to the console
#' @export
dem_cond <- function(x) {
    invisible(.Call('spsintro_dem_cond', PACKAGE = 'spsintro', x))
}

#' An if-else example
#' @param dbh Diameter at breast height in cm
#' @return A diameter class
#' @export
dem_if_else <- function(dbh) {
    .Call('spsintro_dem_if_else', PACKAGE = 'spsintro', dbh)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg <- function(x) {
    .Call('spsintro_find_first_neg', PACKAGE = 'spsintro', x)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg_for <- function(x) {
    .Call('spsintro_find_first_neg_for', PACKAGE = 'spsintro', x)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg_rf <- function(x) {
    .Call('spsintro_find_first_neg_rf', PACKAGE = 'spsintro', x)
}

#' Find first negative element in a vector and return its position
#' @param x A vector of double
#' @return Index of the first negative value
#' @export
find_first_neg_dw <- function(x) {
    .Call('spsintro_find_first_neg_dw', PACKAGE = 'spsintro', x)
}

#' Demonstrate rounding in C++
#' R's built-in \code{round()} function shows a
#' different behaviour than the \code{round()} function of C++
#' @param x A double value to be rounded
#' @return The rounded integer represented as double
#' @export
round_cpp <- function(x) {
    .Call('spsintro_round_cpp', PACKAGE = 'spsintro', x)
}

#' Test Polygon class
#' @return Return nothing
#' @export
use_polygon_class <- function() {
    invisible(.Call('spsintro_use_polygon_class', PACKAGE = 'spsintro'))
}

#' Demonstrates inheritance and dynamic binding
#' @return Return nothing
#' @export
inheritance <- function() {
    invisible(.Call('spsintro_inheritance', PACKAGE = 'spsintro'))
}

#' Naive implementation of bubble sort algorithm
#' @param x A numeric vector which values are sorted in increasing order
#' @return A numeric vector with values sorted in increasing order
bubble_sort <- function(x) {
    .Call('spsintro_bubble_sort', PACKAGE = 'spsintro', x)
}

#'Calculate the factorial of an integer number
#'
#'Meant to use only for teaching purposes not for replacing the built-in
#'function \code{factorial()}.
#'
#'@param n An integer number
#'
#'@details A C++ implementation using a \code{for} loop.
#'
#'@return The factorial of \code{n}
#'@export
#'
#' @examples
#'    fact_cpp(10);
fact_cpp <- function(n) {
    .Call('spsintro_fact_cpp', PACKAGE = 'spsintro', n)
}

#'Calculate the factorial of an integer number
#'
#'Meant to use only for teaching purposes not for replacing the built-in
#'function \code{factorial()}.
#'
#'@param n An integer number
#'
#'@details A C++ implementation using recursion.
#'
#'@return The factorial of \code{n}
#'@export
#'
#' @examples
#'    fact_cpp(10);
fact_rec_cpp <- function(n) {
    .Call('spsintro_fact_rec_cpp', PACKAGE = 'spsintro', n)
}

#'Demonstrate the use of a numeric matrix object from the Rcpp package
#'
#'@param x A numeric matrix
#'
#'@return A new matrix with the same dimensions as \code{x} filled with zeroes
#'@export
use_matrix <- function(x) {
    .Call('spsintro_use_matrix', PACKAGE = 'spsintro', x)
}

#'Demonstrate the use of a list object from the Rcpp package
#'
#'@param x A numeric matrix
#'@param y A numeric vector
#'
#'@return A named list containing both \code{x} and \code{y}.
#'@export
use_list <- function(x, y) {
    .Call('spsintro_use_list', PACKAGE = 'spsintro', x, y)
}

#' Return the area of an irregular polygon
#' @param x A vector of x-coordinates
#' @param y A vector of y-coordinates (positive \code{y}-vaues mean upwards)
#' @return The area of the polygon
#' @export
calc_poly_area <- function(x, y) {
    .Call('spsintro_calc_poly_area', PACKAGE = 'spsintro', x, y)
}

